In [1]:
import torch
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
def activation(x):
    return 1/(1 + torch.exp(-x))

In [3]:
torch.manual_seed(7)

features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [6]:
y1 = activation(torch.sum(features * weights) + bias)
y2 = activation((features * weights).sum() + bias)
y3 = activation(torch.mm(features, weights.view(5,1)) + bias)
y1; y2; y3

tensor([[0.1595]])

tensor([[0.1595]])

tensor([[0.1595]])

In [7]:
torch.manual_seed(7)
features = torch.randn((1,3))

n_input = features.shape[1]
n_hidden = 2
n_output = 1

W1 = torch.randn(n_input, n_hidden)
W2 = torch.randn(n_hidden, n_output)

B1 = torch.randn(1, n_hidden)
B2 = torch.randn(1, n_output)

In [8]:
h = activation(torch.mm(features,W1) + B1)
output = activation(torch.mm(h, W2) + B2)
output

tensor([[0.3171]])

In [9]:
import numpy as np
a = torch.rand(4,3)
a

tensor([[0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691],
        [0.7437, 0.9592, 0.3887],
        [0.2214, 0.3742, 0.1953]])

In [10]:
a_np = np.random.rand(4,3)
a_np

array([[0.63065654, 0.62402499, 0.89361491],
       [0.83526646, 0.42498236, 0.28432911],
       [0.50378005, 0.33148311, 0.76237702],
       [0.59265228, 0.11225076, 0.63103602]])

In [11]:
b = torch.from_numpy(a_np)
b

tensor([[0.6307, 0.6240, 0.8936],
        [0.8353, 0.4250, 0.2843],
        [0.5038, 0.3315, 0.7624],
        [0.5927, 0.1123, 0.6310]], dtype=torch.float64)

In [12]:
b.numpy()

array([[0.63065654, 0.62402499, 0.89361491],
       [0.83526646, 0.42498236, 0.28432911],
       [0.50378005, 0.33148311, 0.76237702],
       [0.59265228, 0.11225076, 0.63103602]])

In [13]:
b.mul_(2)

tensor([[1.2613, 1.2480, 1.7872],
        [1.6705, 0.8500, 0.5687],
        [1.0076, 0.6630, 1.5248],
        [1.1853, 0.2245, 1.2621]], dtype=torch.float64)

In [14]:
a

tensor([[0.7653, 0.1132, 0.8559],
        [0.6721, 0.6267, 0.5691],
        [0.7437, 0.9592, 0.3887],
        [0.2214, 0.3742, 0.1953]])

In [15]:
a_np

array([[1.26131307, 1.24804998, 1.78722982],
       [1.67053292, 0.84996473, 0.56865823],
       [1.00756011, 0.66296622, 1.52475403],
       [1.18530456, 0.22450153, 1.26207204]])