In [1]:
import numpy as np

Estabelecer as funções 

In [12]:
# Função sigmoid como função de ativação
def sigmoid(x):
    return 1/(1+np.exp(-x))

# Função para derivar a função sigmoid
def sigmoid_prime(x):
    return sigmoid(x) * (1 - sigmoid(x))

Estabelecer os dados

In [6]:
# learn rate, input (x), output (y) e cargas iniciais
learnrate = 0.5
x = np.array([1, 2, 3, 4])
y = np.array(0.5)

w = np.array([0.5, -0.5, 0.3, 0.1])


array([ 0.5, -0.5,  0.3,  0.1])

Calcular agora os passos do Gradient Descent

In [17]:
# Calcular a combinação linear
h = np.dot(x, w) 

# h = w[0] * x[0] + w[1] * x[1] + w[2] * x[2] + w[3] * x[3]
# alternativa

Calcula o output, o erro e o error term da rede neural com a função de ativação

In [19]:
# Calcula o output
nn_output = sigmoid(h)

In [20]:
# Calcula o erro
error = y - nn_output

In [21]:
# Calcula o error term
error_term = error * sigmoid_prime(h)

Calcula a mudança nas cargas

In [22]:
del_w = learnrate * error_term * x

In [24]:
print('Neural network output: ')
print(nn_output)
print('Amount of Error: ')
print(error)
print('Original Weights: ')
print(w)
print('Change in Weights: ')
print(del_w)

Neural network output: 
0.689974481128
Amount of Error: 
-0.189974481128
Original Weights: 
[ 0.5 -0.5  0.3  0.1]
Change in Weights: 
[-0.02031869 -0.04063738 -0.06095608 -0.08127477]
